### PR TITLE
Missing property for vehicles...

### PR DESCRIPTION
**Pull request by CoderzNation**
How was this never in the docs?

# Description

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by StanzillaManticore** [comment]
From the data it looks like only FourWheeledVehicle supports it?

**Comment by CoderzNation** [comment]
There seems to be an example that exists for turnRadius in the vehicle API, but it doesn't specify that it needs to be a four wheels vehicle.

**Comment by StanzillaManticore** [comment]
@standardcombo can you check?

**Comment by CommanderFoo** [comment]
`turnRadius` is for `FourWheeledVehicle`. For example, if you try the **Treaded Vehicle** object, it will throw an error as it doesn't support the property.

So the queston I guess, is do we note in the example it is for `FourWheeledVehicle`, or move the example to the **FourWheeledVehicle** API?

I think people are more inclined to look at the **Vehicle** API first, so maybe we note it in the example, and make an extra comment where `turnRadius` is used?

**Comment by StanzillaManticore** [comment]
@PopThosePringles I like your suggestion, can you go ahead with it, please?

**Comment by CommanderFoo** [comment]
I made a PR on the API rep. Added comments and done type checking so the examples will still work and not throw an error if someone tries it with Treaded type.

**Pull request closed without merging**
