### PR TITLE
Add note about Events byte encoding

### PR DESCRIPTION
**Pull request by HyperspaceAlmanac**
# Description

Added in two lines to events API to clarify supported character sets for the broadcast types.

## Type of change

koala

### CODE REVIEW

**Comment by HyperspaceAlmanac** [comment]
Oops, meant to say BroadcastToAllPlayers.

**Review by Montoli — COMMENTED** [review]
I would change this to something like:

If strings are broadcast over the network (via `Events.BroadcastToPlayer` or `Events.BroadcastToServer`) then their characters must have ASCII values within the range 1-127.  Strings used locally and not sent over the network (i. e. `Events.Broadcast`) can use the full 0-255 range.

**Comment by HyperspaceAlmanac** [comment]
The wording above is really good. Sounds great with just that.
I decided to modified it a bit to still place an emphasis on byte encoding, and also mention Events.BroadcastToAllPlayers.

**Comment by StanzillaManticore** [comment]
Awesome, thanks guys!

**Pull request merged**
