### PR TITLE
Updated Game.playerLeftEvent

### PR DESCRIPTION
**Pull request by nicholasforeman**
Many people were getting confused, especially when trying to remove a player from a PlayerList when the event is fired, expecting the player to not be included in the Game.GetPlayers() array.

### CODE REVIEW

**Review by emecklenburg — APPROVED** [review]
This seems like a good thing to add. The player has to still exist in this handler so the creator can clean things up, and as a side effect they exist in GetPlayers() as well. I might add "Note:" to the beginning of the new sentence.

**Comment by nicholasforeman** [comment]
Gotcha. I was considering saying that if they want to handle it without the player that was leaving then to use the ignorePlayers filter in Game.GetPlayers() as in the documentation, however, it seemed a bit long-winded.

**Comment by nicholasforeman** [comment]
Is there any way I can edit the pull request to include "Note:" per your suggestion or would I have to make a new request/rely on someone else to implement it in the merge pull request?

**Comment by Montoli** [comment]
I'd even go longer-winded, honestly. :D  Something like:

> Fired when a player has disconnected from the game or their character has been destroyed. This event fires before the player has been removed, so functions such as `Game.GetPlayers()` will still include the player that is about to leave.

This is definitely good info to include though!  I actually ran into it last week myself.

**Comment by nicholasforeman** [comment]
Perhaps something like this would work then:
> Fired when a player has disconnected from the game or their character has been destroyed. This event fires before the player has been removed, so functions such as Game.GetPlayers() will still include the player that is about to leave unless using the ignorePlayers filter within the parameters.

**Comment by Montoli** [comment]
👍

**Review by Montoli — CHANGES_REQUESTED** [review]
Change to your most recent suggestion and we're gold!

**Review by Montoli — APPROVED** [review]

**Comment by StanzillaManticore** [comment]
Thanks!

**Comment by Montoli** [comment]
Thanks for helping us improve the documentation!

**Pull request merged**
